### ISSUE TITLE
免费版灾难性错误 无法启动

### ISSUE THREAD

**Issue by CberYellowstone** [CAIMEOX/FastBuilder#3]
[root@localhost FastBuilder]# node Main.js 
/root/FastBuilder/node_modules/meowslib/src/collector.js:18
  async getPosition(target){
        ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/FastBuilder/node_modules/meowslib/index.js:5:19)

**Comment by CberYellowstone** [comment]
@CAIMEOX

**Comment by CAIMEOX** [comment]
更新NodeJS
