### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by armymenrts** [CAIMEOX/FastBuilder#6]
TypeError: Cannot read property 'address' of undefined
    at getHost (D:\FastBuilder-master\node_modules\meowslib\src\mcpews.js:327:39)
    at new WSServer (D:\FastBuilder-master\node_modules\meowslib\src\mcpews.js:11:34)
    at Object.<anonymous> (D:\FastBuilder-master\Main.js:17:11)

**Comment by Torrekie** [comment]
Try latest version.
